name: Show github Action Variables
run-name: github.actor is ${{ github.actor }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.event_name = ${{ github.event_name }}"
      - run: echo "runner.os = ${{ runner.os }}"
      - run: echo "github.ref = ${{ github.ref }} ; github.repository = ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          pwd
      - run: echo "This job's status is ${{ job.status }}."
